### ISSUE TITLE
Structure proposals

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/awesome-cryptography#1]
What are the topics to cover? 

That's how I see it:
* theoretical part
  * algorithms
  * books
  * let's call it "general encryption-science"
* frameworks and libs
  * python
  * js
  * so on...
* web apps
  * keybase.io, etc

**Comment by xymfrx** [comment]
What about a practical cryptography? Add some tools for encrypt and decrypt or maybe training part, where we can add a services like [CryptoClub](http://www.cryptoclub.org/games) and other training games (CTF, etc)

**Comment by sobolevn** [comment]
Tools can be also stored inside the `frameworks and libs`. Things like `gpg` and `lets-encrypt` will suite perfectly.

**Comment by sobolevn** [comment]
Books and other resources should be separated by language.
