### ISSUE TITLE
Add keys.pub

### ISSUE THREAD

**Issue by freddy-m** [sobolevn/awesome-cryptography#110]
[keys.pub](https://keys.pub/) is a key management tool similar to keybase.

**Comment by lk-geimfari** [comment]
I'm gonna say that this is a little bit disquieting:

> This project is in development and has not been audited or reviewed. Use at your own risk.

**Comment by FreddyMarsden** [comment]
Similarly, [Keyoxide](https://keyoxide.org/) and [decentralised proofs](https://metacode.biz/openpgp/) might be worth a look...
