### ISSUE TITLE
shields/badges?

### ISSUE THREAD

**Issue by robjtede** [sobolevn/awesome-cryptography#56]
Looking at the Rust libraries some of them are pretty inactive. Wondering if using shields is a good idea for this. Eg. the Rust `rust-openssl` and `suruga` library entries could look like this.

- [rust-openssl](https://github.com/sfackler/rust-openssl) - OpenSSL bindings for Rust. ![GitHub last commit](https://img.shields.io/github/last-commit/sfackler/rust-openssl.svg)
- [suruga](https://github.com/klutzy/suruga) - TLS 1.2 implementation in Rust. ![GitHub last commit](https://img.shields.io/github/last-commit/klutzy/suruga.svg)

or a more radical change being converting the list to a table layout which could include more shields if needed like number of open issues?

| Repo | Description | Info |
|--|--|--|
| [rust-openssl](https://github.com/sfackler/rust-openssl) | OpenSSL bindings for Rust. | ![GitHub last commit](https://img.shields.io/github/last-commit/sfackler/rust-openssl.svg)
| [suruga](https://github.com/klutzy/suruga) | TLS 1.2 implementation in Rust. | ![GitHub last commit](https://img.shields.io/github/last-commit/klutzy/suruga.svg) |

I feel like the freshness of a crypto repo is a pretty important factor for choosing, personally.

**Comment by sobolevn** [comment]
I like badges!

But sometimes there can be too much badges. Maybe just removing some outdated packages?
